version: '3.4'
services:
  react:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./app:/usr/app/streamUs
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 3000:3000
