version: '3.4'
services:
  react:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - $PWD/app:/usr/app/streamUs
      - $PWD/app/node_modules
    ports:
      - 3000:3000
