env:
  browser: true
  es6: true
  node: true
extends: airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {
  "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
  "import/no-unresolved": "off"
}
settings:
  import/resolver:
    node:
      extensions:
        # if unset, default is just '.js', but it must be re-added explicitly if set 
        - .js
        - .android.js
        - .ios.js